name: medbook

services:
  # GATEWAY
  gateway:
    image: nginx:stable-alpine
    container_name: gateway
    depends_on:
      users:
        condition: service_healthy
    ports:
      - "3000:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - gateway
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/health-check || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  # USERS
  users:
    build:
      context: ./services/medbook-userservice
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      users-db:
        condition: service_healthy
    command: ["/bin/sh", "-c", "diesel migration run && /app/server"]
    networks:
      - gateway
      - users_net
      - backend
    env_file:
      - ./.users-service.env
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:3000/health-check > /dev/null"]
      interval: 10s
      timeout: 3s
      retries: 5

  users-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: users_db
    volumes:
      - users_db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - users_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d users"]
      interval: 10s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer:latest
    expose:
      - "8080"
    ports:
      - "7070:8080"
    networks:
      - gateway
      - users_net

networks:
  gateway:
    driver: bridge
  backend:
    driver: bridge
  users_net:
    driver: bridge

volumes:
  users_db_data:
  orders_db_data: